server:
  port: 10010

spring:
  application:
    name: eureka-server
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10011/eureka

